In [111]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
df=pd.read_csv('dataset/16-diabetes.csv')
import warnings
warnings.filterwarnings("ignore")

In [112]:
X=df.drop("Outcome",axis=1)
y=df["Outcome"]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=15)

In [113]:
col_to_fill = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
for col in col_to_fill:
    median_value=X_train[X_train[col] != 0][col].median()
    X_train[col] = X_train[col].replace(0, median_value)
    X_test[col] = X_test[col].replace(0, median_value) 

In [114]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [115]:
from sklearn.ensemble import AdaBoostClassifier
ada=AdaBoostClassifier()
ada.fit(X_train_scaled,y_train)
y_pred=ada.predict(X_test_scaled)

In [116]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.7532467532467533
Confusion Matrix:
 [[87 21]
 [17 29]]
Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.81      0.82       108
           1       0.58      0.63      0.60        46

    accuracy                           0.75       154
   macro avg       0.71      0.72      0.71       154
weighted avg       0.76      0.75      0.76       154



In [117]:
X=df.drop(["Insulin","SkinThickness","Outcome"],axis=1)
y=df["Outcome"]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [118]:
for col in ['Glucose', 'BloodPressure','BMI']:
    median_value=X_train[X_train[col] != 0][col].median()
    X_train[col] = X_train[col].replace(0, median_value)
    X_test[col] = X_test[col].replace(0, median_value)

In [119]:
X_train.describe()

Pregnancies     Glucose  BloodPressure         BMI  \
count   614.000000  614.000000     614.000000  614.000000   
mean      3.742671  121.815961      72.229642   32.348208   
std       3.313264   30.104012      12.099278    6.935618   
min       0.000000   44.000000      24.000000   18.200000   
25%       1.000000  100.000000      64.000000   27.325000   
50%       3.000000  118.000000      72.000000   32.000000   
75%       6.000000  139.000000      80.000000   36.375000   
max      17.000000  199.000000     122.000000   67.100000   

       DiabetesPedigreeFunction         Age  
count                614.000000  614.000000  
mean                   0.469168   32.907166  
std                    0.336847   11.503437  
min                    0.078000   21.000000  
25%                    0.241500   24.000000  
50%                    0.372500   29.000000  
75%                    0.613750   40.000000  
max                    2.420000   81.000000

In [120]:
X_test.describe()

Pregnancies     Glucose  BloodPressure         BMI  \
count   154.000000  154.000000     154.000000  154.000000   
mean      4.253247  121.051948      73.012987   32.860390   
std       3.567394   31.825873      12.105196    6.635854   
min       0.000000   62.000000      48.000000   18.400000   
25%       1.250000   96.000000      64.250000   28.425000   
50%       3.000000  112.000000      72.000000   32.850000   
75%       7.000000  146.000000      78.000000   36.975000   
max      13.000000  197.000000     114.000000   53.200000   

       DiabetesPedigreeFunction         Age  
count                154.000000  154.000000  
mean                   0.482675   34.571429  
std                    0.309155   12.685155  
min                    0.102000   21.000000  
25%                    0.247250   24.000000  
50%                    0.372500   29.500000  
75%                    0.679250   42.000000  
max                    1.390000   67.000000

In [121]:
ada=AdaBoostClassifier()
ada.fit(X_train_scaled,y_train)
y_pred=ada.predict(X_test_scaled)

In [122]:
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Confusion Matrix :\n", confusion_matrix(y_test, y_pred))
print("Classification Report :\n", classification_report(y_test, y_pred))

Accuracy : 0.6233766233766234
Confusion Matrix :
 [[92  7]
 [51  4]]
Classification Report :
               precision    recall  f1-score   support

           0       0.64      0.93      0.76        99
           1       0.36      0.07      0.12        55

    accuracy                           0.62       154
   macro avg       0.50      0.50      0.44       154
weighted avg       0.54      0.62      0.53       154



In [123]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
rf=RandomForestClassifier()
knn=KNeighborsClassifier()
lr=LogisticRegression()

In [124]:
X=df.drop("Outcome",axis=1)
y=df["Outcome"]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=15)
col_to_fill = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
for col in col_to_fill:
    median_value=X_train[X_train[col] != 0][col].median()
    X_train[col] = X_train[col].replace(0, median_value)
    X_test[col] = X_test[col].replace(0, median_value)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [125]:
# her modelin hiperparametre olmadan sonucu
for model in [rf, knn, lr]:
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)
    print(f"Accuracy for {model}: {accuracy_score(y_test, y_pred)}")
    print(f"Confusion Matrix for {model}:\n", confusion_matrix(y_test, y_pred))
    print(f"Classification Report for {model}:\n", classification_report(y_test, y_pred))
    print("\n")

Accuracy for RandomForestClassifier(): 0.7272727272727273
Confusion Matrix for RandomForestClassifier():
 [[84 24]
 [18 28]]
Classification Report for RandomForestClassifier():
               precision    recall  f1-score   support

           0       0.82      0.78      0.80       108
           1       0.54      0.61      0.57        46

    accuracy                           0.73       154
   macro avg       0.68      0.69      0.69       154
weighted avg       0.74      0.73      0.73       154



Accuracy for KNeighborsClassifier(): 0.6948051948051948
Confusion Matrix for KNeighborsClassifier():
 [[81 27]
 [20 26]]
Classification Report for KNeighborsClassifier():
               precision    recall  f1-score   support

           0       0.80      0.75      0.78       108
           1       0.49      0.57      0.53        46

    accuracy                           0.69       154
   macro avg       0.65      0.66      0.65       154
weighted avg       0.71      0.69      0.70      

In [126]:
# her model için parametre aralığını tanımla
param_grid_all = {
    'ada': {
        'n_estimators': [50, 100, 200],
        'learning_rate': [0.01, 0.1, 1, 5, 10],
        'estimator': [None, 'DecisionTreeClassifier', 'RandomForestClassifier'],
        'algorithm': ['SAMME', 'SAMME.R']
    },
    'rf': {
        'n_estimators': [50, 100, 200],
        'max_depth': [None, 10, 20],
        'min_samples_split': [2, 5, 10],
        'criterion': ['gini', 'entropy'],
        'max_features': ['auto', 'sqrt', 'log2']
    },
    'knn': {
        'n_neighbors': [3, 5, 7],
        'weights': ['uniform', 'distance'],
        'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute']
    },
    'lr': {
        'C': [0.01, 0.1, 1],
        'solver': ['liblinear', 'saga', 'lbfgs'],
        'penalty': ['l1', 'l2', 'elasticnet', 'none']
    }
}

In [127]:
# her modeli döngü içinde eğit ve en iyi parametreleri bul
for model in ['ada', 'rf', 'knn', 'lr']:
    if model == 'ada':
        grid_search = GridSearchCV(ada, param_grid_all[model], cv=5, n_jobs=-1)
    if model == 'rf':
        grid_search = GridSearchCV(rf, param_grid_all[model], cv=5, n_jobs=-1)
    elif model == 'knn':
        grid_search = GridSearchCV(knn, param_grid_all[model], cv=5, n_jobs=-1)
    elif model == 'lr':
        grid_search = GridSearchCV(lr, param_grid_all[model], cv=5, n_jobs=-1)

    grid_search.fit(X_train_scaled, y_train)
    print(f"Best parameters for {model}: {grid_search.best_params_}")
    print(f"Best score for {model}: {grid_search.best_score_:.4f}")
    y_pred = grid_search.predict(X_test_scaled)
    print(f"Test Accuracy for {model}: {accuracy_score(y_test, y_pred):.4f}")
    print(f"Confusion Matrix for {model}:\n{confusion_matrix(y_test, y_pred)}")
    print(f"Classification Report for {model}:\n{classification_report(y_test, y_pred)}\n")

Best parameters for ada: {'algorithm': 'SAMME', 'estimator': None, 'learning_rate': 1, 'n_estimators': 100}
Best score for ada: 0.7557
Test Accuracy for ada: 0.7727
Confusion Matrix for ada:
[[88 20]
 [15 31]]
Classification Report for ada:
              precision    recall  f1-score   support

           0       0.85      0.81      0.83       108
           1       0.61      0.67      0.64        46

    accuracy                           0.77       154
   macro avg       0.73      0.74      0.74       154
weighted avg       0.78      0.77      0.78       154


Best parameters for rf: {'criterion': 'entropy', 'max_depth': 20, 'max_features': 'log2', 'min_samples_split': 2, 'n_estimators': 50}
Best score for rf: 0.7883
Test Accuracy for rf: 0.7273
Confusion Matrix for rf:
[[84 24]
 [18 28]]
Classification Report for rf:
              precision    recall  f1-score   support

           0       0.82      0.78      0.80       108
           1       0.54      0.61      0.57        46

    